detection_phase:
  hand_to_fuse: left
  arm_to_fuse: left
  num_person_to_detect: 1
  model_list:
    - mediapipe
    - mmpose
  model_selection_id: 0
  mediapipe:
    convert_color_channel: true
    hand_detection:
      is_enable: true
      min_detection_confidence: 0.3
      min_presence_confidence: 0.3
      min_tracking_confidence: 0.3
      num_hand: 2
      model_asset_path: /home/giakhang/dev/Hand_pose_estimation_3D/model_path/hand_landmarker.task
      hand_landmarks:
        - WRIST
        - THUMB_CMC
        - THUMB_MCP
        - THUMB_IP
        - THUMB_TIP
        - INDEX_FINGER_MCP
        - INDEX_FINGER_PIP
        - INDEX_FINGER_DIP
        - INDEX_FINGER_TIP
        - MIDDLE_FINGER_MCP
        - MIDDLE_FINGER_PIP
        - MIDDLE_FINGER_DIP
        - MIDDLE_FINGER_TIP
        - RING_FINGER_MCP
        - RING_FINGER_PIP
        - RING_FINGER_DIP
        - RING_FINGER_TIP
        - PINKY_MCP
        - PINKY_PIP
        - PINKY_DIP
        - PINKY_TIP
    body_detection:
      is_enable: true
      min_detection_confidence: 0.5
      min_tracking_confidence: 0.5
      visibility_threshold: 0.2
      model_asset_path: /home/giakhang/dev/Hand_pose_estimation_3D/model_path/pose_landmarker_lite.task
      body_landmarks:
        - nose
        - left eye (inner)
        - left eye
        - left eye (outer)
        - right eye (inner)
        - right eye
        - right eye (outer)
        - left ear
        - right ear
        - mouth (left)
        - mouth (right)
        - left shoulder
        - right shoulder
        - left elbow
        - right elbow
        - left wrist
        - right wrist
        - left pinky
        - right pinky
        - left index
        - right index
        - left thumb
        - right thumb
        - left hip
        - right hip
        - left knee
        - right knee
        - left ankle
        - right ankle
        - left heel
        - right heel
        - left foot index
        - right foot index
  mmpose:
    convert_color_channel: false
    landmark_threshold_to_draw: 0.5
    person_detection:
      is_enable: true
      person_detector_config: /home/giakhang/dev/pose_sandbox/mmpose/projects/rtmpose/rtmdet/person/rtmdet_nano_320-8xb32_coco-person.py
      person_detector_weight: https://download.openmmlab.com/mmpose/v1/projects/rtmpose/rtmdet_nano_8xb32-100e_coco-obj365-person-05d8511e.pth
    pose_estimation:
      is_enable: true
      left_camera_pose_estimator_config: /home/giakhang/dev/pose_sandbox/mmpose/configs/wholebody_2d_keypoint/rtmpose/coco-wholebody/rtmpose-m_8xb64-270e_coco-wholebody-256x192.py
      left_camera_pose_estimator_weight: /home/giakhang/Downloads/rtmpose-m_simcc-ucoco_dw-ucoco_270e-256x192-c8b76419_20230728.pth
      right_camera_pose_estimator_config: /home/giakhang/dev/pose_sandbox/mmpose/configs/wholebody_2d_keypoint/rtmpose/coco-wholebody/rtmpose-m_8xb64-270e_coco-wholebody-256x192.py
      right_camera_pose_estimator_weight: /home/giakhang/Downloads/rtmpose-m_simcc-ucoco_dw-ucoco_270e-256x192-c8b76419_20230728.pth
      #left_camera_pose_estimator_config: /home/giakhang/dev/pose_sandbox/rtmpose-m_4_left_cam.py
      #left_camera_pose_estimator_weight: /home/giakhang/dev/pose_sandbox/best_left_camera_rtmpose-m_weight.pth
      #right_camera_pose_estimator_config: /home/giakhang/dev/pose_sandbox/rtmpose-m_4_right_cam.py
      #right_camera_pose_estimator_weight: /home/giakhang/dev/pose_sandbox/best_right_camera_rtmpose-m_weight.pth
  fusing_landmark_dictionary:
    - left shoulder
    - left elbow
    - left hip
    - right shoulder
    - right hip
    - WRIST
    - THUMB_CMC
    - THUMB_MCP
    - THUMB_IP
    - THUMB_TIP
    - INDEX_FINGER_MCP
    - INDEX_FINGER_PIP
    - INDEX_FINGER_DIP
    - INDEX_FINGER_TIP
    - MIDDLE_FINGER_MCP
    - MIDDLE_FINGER_PIP
    - MIDDLE_FINGER_DIP
    - MIDDLE_FINGER_TIP
    - RING_FINGER_MCP
    - RING_FINGER_PIP
    - RING_FINGER_DIP
    - RING_FINGER_TIP
    - PINKY_MCP
    - PINKY_PIP
    - PINKY_DIP
    - PINKY_TIP

fusing_phase:
  fusing_methods:
    - transformer_encoder
    - minimize_distance
  fusing_selection_id: 0
  transformer_encoder: 
    sequence_length: 5
    input_dim: 322
    output_dim: 153
    num_heads: 7
    num_encoder_layers: 6
    dim_feedforward: 512
    dropout: 0.1
    model_weight_path: /home/giakhang/dev/pose_sandbox/Hand_pose_estimation_3D/arm_and_hand/best_model_2024-08-15-14:03.pth
  minimize_distance:
    algo_name: L-BFGS-B
    tolerance: 1e-10

camera:
  frame_calibrated_size:
    width: 1280
    height: 720
  left_camera:
    mxid: "18443010E13D641200"
    left_camera_calibration_path: /home/giakhang/dev/pose_sandbox/Hand_pose_estimation_3D/camera_calibration/left_oak_calibration.npz
  right_camera:
    mxid: "18443010613E940F00"
    right_camera_calibration_path: /home/giakhang/dev/pose_sandbox/Hand_pose_estimation_3D/camera_calibration/right_oak_calibration.npz

process_frame:
  frame_size:  # the higher resolution is, the futher distance which can be processed by the system
    width: 1920
    height: 1080

utilities:
  draw_landmarks: true       # Draw landmarks on rgb image
  plot_3d: true              # Plot the hand landmarks on open3d
  save_angles: false
  save_landmarks: false      # Write landmarks to to file, save_landmarks must be runned with manual computation (dont use neural net.) for better ground truth
  save_images: false

debugging_mode:
  draw_xyz: false
  show_left_arm_angle_j1: false       # Plotting left arm joint 1 and its reference vector to debug (visualize)
  show_left_arm_angle_j2: false       # Plotting left arm joint 2 and its reference vector to debug (visualize)
  show_left_arm_angle_j3: false       # Plotting left arm joint 3 and its reference vector to debug (visualize)
  show_left_arm_angle_j4: false       # Plotting left arm joint 4 and its reference vector to debug (visualize)
  show_left_arm_angle_j5: false       # Plotting left arm joint 5 and its reference vector to debug (visualize)
  show_left_arm_angle_j6: false       # Plotting left arm joint 6 and its reference vector to debug (visualize)
  ref_vector_color: 
    - 1
    - 0
    - 0
  joint_vector_color: 
    - 0
    - 0
    - 1

