camera:
  realsense:
    rgb:
      width: 1280
      height: 720
    depth:
      width: 640
      height: 360
    opposite_camera_calibration_path: /home/giakhang/dev/Hand_pose_estimation_3D/camera_calibration/rs_calibration.npz
  oak:
    stereo: 
      width: 640
      height: 360
    rightside_camera_calibration_path: /home/giakhang/dev/Hand_pose_estimation_3D/camera_calibration/oak_calibration.npz

process_frame:
  frame_color_format: bgr
  frame_size:
    width: 640
    height: 360
  depth_smoothing:
    sliding_window_size: 12          # Diameter of each pixel neighborhood
    sigma_color: 25                  # Filter sigma in the color space for bilateral
    sigma_space: 25                  # Filter sigma in the coordinate space for bilateral

utilities:
  draw_landmarks: true       # Draw landmarks on rgb image
  plot_3d: true              # Plot the hand landmarks on open3d
  save_landmarks: false      # Write landmarks to to file, save_landmarks must be runned with manual computation (dont use neural net.) for better ground truth

hand_landmark_detection:
  is_enable: true
  hand_to_fuse:
    left: true
    right: false
    both: false
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
  visibility_threshold: 0.2
  num_hand: 2
  model_asset_path: /home/giakhang/dev/Hand_pose_estimation_3D/model_path/hand_landmarker.task

arm_landmark_detection:
  is_enable: true
  arm_to_fuse:
    left: true
    right: false
    both: false
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5
  visibility_threshold: 0.2
  num_pose: 1
  model_asset_path: /home/giakhang/dev/Hand_pose_estimation_3D/model_path/pose_landmarker_heavy.task
  pose_landmarks:
    - nose
    - left eye (inner)
    - left eye
    - left eye (outer)
    - right eye (inner)
    - right eye
    - right eye (outer)
    - left ear
    - right ear
    - mouth (left)
    - mouth (right)
    - left shoulder
    - right shoulder
    - left elbow
    - right elbow
    - left wrist
    - right wrist
    - left pinky
    - right pinky
    - left index
    - right index
    - left thumb
    - right thumb
    - left hip
    - right hip
    - left knee
    - right knee
    - left ankle
    - right ankle
    - left heel
    - right heel
    - left foot index
    - right foot index
